version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to docker hub
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t my-app-image .
      - echo Tagging the Docker image...
      - docker tag my-app-image $DOCKER_USERNAME/my-app-image:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Docker Hub...
      - docker push $DOCKER_USERNAME/my-app-image:latest
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  discard-paths: yes