name: InfraStructure Deployment
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
    workflow_dispatch:
    

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs: 
    Plan:
        runs-on: ubuntu-latest
        steps:
            - name: Start Plan
              run: echo "Hello Plan!!"

            - name: Print Github
              run: echo "Context Object github print ${{ toJson(github) }}"
